### ISSUE TITLE
New samples protect against this specific tool

### ISSUE THREAD

**Issue by lucawint** [linuxct/malninstall#1]
Hey there,

Just wanted to let you know I've found a FluBot sample that specifically protects itself against being uninstalled by your app.

SHA256: `dd1f6fbed6f5913831aef79533d24f7de3f0518c8d1844c9c094d3ba03aebe17`
Package name: `com.didiglobal.passenger`

Related decompiled code in the sample:

`
if (charSequence.equals("space.linuxct.malninstall")) {
        System.out.println("Держи еще 25$, мальчик :))");
        i2 = 1;
}
`

Also discovered some more package names the malware uses while analyzing samples:

`com.eg.android.AlipayGphone`
`party.timber.anxiety`

**Comment by linuxct** [comment]
The new malninstall located at [malninstall.linuxct.space](malninstall.linuxct.space) should cover these cases. You can check the source code at [`linuxct/malninstall-configuration`](https://github.com/linuxct/malninstall-configuration) and [`linuxct/malninstall-frontend`](https://github.com/linuxct/malninstall-frontend)
